# Generated by Django 5.0.14 on 2025-10-05 19:25

import django.db.models.deletion
import game.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        max_length=5,
                        unique=True,
                        validators=[game.models.validate_uppercase_5letter],
                    ),
                ),
            ],
            options={
                "ordering": ["text"],
            },
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("won", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="games",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="games",
                        to="game.word",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="DailyQuota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField()),
                ("words_started_count", models.PositiveSmallIntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_quotas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["user", "date"], name="game_dailyq_user_id_f5f024_idx")
                ],
                "unique_together": {("user", "date")},
            },
        ),
        migrations.CreateModel(
            name="Guess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        max_length=5, validators=[game.models.validate_uppercase_5letter]
                    ),
                ),
                ("index", models.PositiveSmallIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guesses",
                        to="game.game",
                    ),
                ),
            ],
            options={
                "ordering": ["game", "index"],
                "indexes": [
                    models.Index(fields=["game", "index"], name="game_guess_game_id_df7d2c_idx")
                ],
                "unique_together": {("game", "index")},
            },
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(fields=["user", "-started_at"], name="game_game_user_id_e7623a_idx"),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(fields=["started_at"], name="game_game_started_9f89d1_idx"),
        ),
    ]
