name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run ruff
        run: |
          ruff check .

      - name: Run black
        run: |
          black --check .

      - name: Run migrations
        run: |
          python manage.py migrate --noinput

      - name: Seed database
        run: |
          python manage.py seed_words

      - name: Run tests
        run: |
          pytest
        env:
          SECRET_KEY: test-secret-key-for-ci
          DEBUG: "False"
